spring:
  application:
    name: HotelBooking
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    url: jdbc:postgresql://${DB_HOST:${DB_HOST:-localhost}}:${DB_PORT:-5432}/${DB_NAME:-HotelBooking}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
    show-sql: false



jwt:
  secretKey: ${JWT_SECRET_KEY}
  accessToken:
    expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:600000}
  refreshToken:
    expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800000}